image: quay.io/glennhickey/cactus-ci-base:latest

before_script:
  - whoami
  - sudo apt-get -q -y update
  - sudo apt-get -q -y install redis-server libhiredis0.13 libhiredis-dev liblzma-dev libxml2-dev
  # Configure Docker to use a mirror for Docker Hub and restart the daemon
  # Set the registry as insecure because it is probably cluster-internal over plain HTTP.
  - |
    if [[ ! -z "${DOCKER_HUB_MIRROR}" ]] ; then
        echo "{\"registry-mirrors\": [\"${DOCKER_HUB_MIRROR}\"], \"insecure-registries\": [\"${DOCKER_HUB_MIRROR##*://}\"]}" | sudo tee /etc/docker/daemon.json
    fi
  - startdocker || true
  - docker info

after_script:
  - stopdocker || true
  
stages:
  - test

test-job:
  stage: test
  script:
    - git submodule update --init --recursive
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - pip install -r toil-requirement.txt
    - build-tools/downloadPangenomeTools
    - pip install -U .	 
    - make -j 8 evolver_test
  artifacts:
    # Let Gitlab see the junit report
    #reports:
    #  junit: test-report.xml
    #when: always
  
